### ISSUE TITLE
Convert hard coded, environment specific values to envars

### ISSUE THREAD

**Issue by philipcofc** [philipcofc/docker-elk#1]
While not yet committed and pushed up, we'll likely need a way to pass environment variables to the containers to leverage Brice's nginx proxy setup. 

Locally I have the following, as an example:

``` YAML
kibana:
  environment: 
    VIRTUAL_HOST: "kibana.node-q.********.com"
```

In this specific instance, we may be able export envars at run time. 

This may also apply to #2 depending on what direction we want to go, although not environment specific. 

Thinking out loud.
